# Generated by Django 6.0.3 on 2026-03-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_acceptant_alter_quote_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_date']},
        ),
    ]
