# Generated by Django 6.0.3 on 2026-03-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0003_alter_quote_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.IntegerField(choices=[(1, "Is pending"), (2, "Is rejected"), (3, "Is approved")], default=1),
        ),
    ]
