# Generated by Django 6.0.3 on 2026-03-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0004_alter_quote_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Is pending"), (2, "Is rejected"), (3, "Is approved")], db_index=True, default=1
            ),
        ),
    ]
